// src/components/PauseMenu.tsx
import { Play, RotateCcw, Home, Pause } from 'lucide-react';

interface PauseMenuProps {
  onResume: () => void;
  onRestart: () => void;
  onMainMenu: () => void;
}

export default function PauseMenu({ onResume, onRestart, onMainMenu }: PauseMenuProps) {
  return (
    <div
      className="absolute inset-0 flex items-center justify-center z-50"
      style={{
        background: 'rgba(0,0,0,0.75)',
        backdropFilter: 'blur(6px)',
      }}
    >
      <div className="text-center px-6">
        <div className="mb-6 flex justify-center">
          <div
            className="rounded-full p-6 border-2"
            style={{
              background: 'rgba(20,20,15,0.9)',
              borderColor: 'rgba(200,150,50,0.5)',
              boxShadow: '0 0 20px rgba(200,150,50,0.15)',
            }}
          >
            <Pause size={48} style={{ color: '#daa520' }} />
          </div>
        </div>

        <h2
          className="text-4xl font-black text-white mb-8 tracking-wider"
          style={{ textShadow: '0 0 10px rgba(255,255,255,0.2)' }}
        >
          游戏暂停
        </h2>

        <div className="space-y-3 max-w-xs mx-auto">
          <button
            onClick={onResume}
            className="w-full py-3 px-6 text-white font-bold rounded-lg transition-all transform hover:scale-105 flex items-center justify-center gap-2 border"
            style={{
              background: 'linear-gradient(135deg, #1a4a1a 0%, #2d6a2d 50%, #1a4a1a 100%)',
              borderColor: 'rgba(50,150,50,0.4)',
              boxShadow: '0 0 15px rgba(50,150,50,0.15), 0 4px 12px rgba(0,0,0,0.4)',
            }}
          >
            <Play size={18} fill="currentColor" />
            继续游戏
          </button>
          <button
            onClick={onRestart}
            className="w-full py-3 px-6 text-white font-bold rounded-lg transition-all transform hover:scale-105 flex items-center justify-center gap-2 border"
            style={{
              background: 'linear-gradient(135deg, #6b4c14 0%, #8b6914 50%, #6b4c14 100%)',
              borderColor: 'rgba(200,150,50,0.4)',
              boxShadow: '0 0 15px rgba(200,150,50,0.1), 0 4px 12px rgba(0,0,0,0.4)',
            }}
          >
            <RotateCcw size={18} />
            重新开始
          </button>
          <button
            onClick={onMainMenu}
            className="w-full py-3 px-6 text-gray-300 font-bold rounded-lg transition-all flex items-center justify-center gap-2 border"
            style={{
              background: 'rgba(30,30,30,0.9)',
              borderColor: 'rgba(100,100,100,0.3)',
            }}
          >
            <Home size={18} />
            返回主菜单
          </button>
        </div>
      </div>
    </div>
  );
}

// static/guangying/src/components/PauseMenu.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Play, RotateCcw, LayoutGrid, Home } from 'lucide-vue-next'
import { useGameStore } from '@/store/gameStore'

const emit = defineEmits<{
  (e: 'resume'): void
  (e: 'restart'): void
  (e: 'levelSelect'): void
  (e: 'mainMenu'): void
}>()

const gameStore = useGameStore()

const isVisible = computed(() => {
  return gameStore.currentScene === 'paused'
})

const handleResume = () => {
  emit('resume')
}

const handleRestart = () => {
  emit('restart')
}

const handleLevelSelect = () => {
  emit('levelSelect')
}

const handleMainMenu = () => {
  emit('mainMenu')
}
</script>

<template>
  <Transition name="fade">
    <div
      v-if="isVisible"
      class="pause-overlay fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm"
    >
      <Transition name="scale">
        <div
          v-if="isVisible"
          class="pause-panel relative bg-gradient-to-br from-slate-900/95 to-slate-800/95 rounded-2xl p-8 border border-white/10 shadow-2xl max-w-md w-full mx-4"
        >
          <div class="absolute inset-0 rounded-2xl bg-gradient-to-br from-yellow-500/5 to-purple-500/5 pointer-events-none" />

          <div class="relative">
            <h2 class="text-3xl font-bold text-center text-white mb-2">游戏暂停</h2>
            <p class="text-center text-gray-400 mb-8">休息一下，随时继续冒险</p>

            <div class="space-y-4">
              <button
                class="pause-btn w-full flex items-center justify-center gap-3 px-6 py-4 bg-gradient-to-r from-green-500 to-emerald-500 hover:from-green-400 hover:to-emerald-400 text-white font-bold rounded-xl transition-all duration-200 active:scale-95 shadow-lg shadow-green-500/25"
                @click="handleResume"
              >
                <Play class="w-5 h-5 fill-current" />
                继续游戏
              </button>

              <button
                class="pause-btn w-full flex items-center justify-center gap-3 px-6 py-4 bg-gradient-to-r from-blue-500 to-cyan-500 hover:from-blue-400 hover:to-cyan-400 text-white font-bold rounded-xl transition-all duration-200 active:scale-95 shadow-lg shadow-blue-500/25"
                @click="handleRestart"
              >
                <RotateCcw class="w-5 h-5" />
                重新开始
              </button>

              <button
                class="pause-btn w-full flex items-center justify-center gap-3 px-6 py-4 bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-400 hover:to-orange-400 text-white font-bold rounded-xl transition-all duration-200 active:scale-95 shadow-lg shadow-amber-500/25"
                @click="handleLevelSelect"
              >
                <LayoutGrid class="w-5 h-5" />
                关卡选择
              </button>

              <button
                class="pause-btn w-full flex items-center justify-center gap-3 px-6 py-4 bg-white/10 hover:bg-white/20 text-white font-bold rounded-xl transition-all duration-200 active:scale-95 border border-white/10"
                @click="handleMainMenu"
              >
                <Home class="w-5 h-5" />
                返回主菜单
              </button>
            </div>

            <p class="text-center text-gray-500 text-sm mt-6">
              按 <kbd class="px-2 py-1 bg-white/10 rounded text-gray-300">ESC</kbd> 继续游戏
            </p>
          </div>
        </div>
      </Transition>
    </div>
  </Transition>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

.scale-enter-active,
.scale-leave-active {
  transition: all 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
}

.scale-enter-from,
.scale-leave-to {
  opacity: 0;
  transform: scale(0.9);
}

.pause-btn {
  position: relative;
  overflow: hidden;
}

.pause-btn::before {
  content: '';
  position: absolute;
  top: 0;
  left: -100%;
  width: 100%;
  height: 100%;
  background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);
  transition: left 0.5s ease;
}

.pause-btn:hover::before {
  left: 100%;
}

.pause-panel {
  animation: float 6s ease-in-out infinite;
}

@keyframes float {
  0%, 100% {
    transform: translateY(0);
  }
  50% {
    transform: translateY(-10px);
  }
}
</style>
